[package]
name = "wordle-solver"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3.4", features = [ "Document", "Element", "HtmlElement", "Node", "Window" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
